name: Get Exchange Rate Data
on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - main

jobs:
  get-data:
    permissions:
      contents: write
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: |
          npm install

      - name: Get Exchange Rate Data
        run: |
          curl -o data-informal.json https://exchange-rate.decubba.com/api/v2/informal/target/cup.json
          curl -o data-formal.json https://exchange-rate.decubba.com/api/v2/formal/target/cup.json

      - name: Push Data to Repo
        run: |
          mkdir -p dist/data/$(date +%Y-%m-%d)
          cp data-informal.json dist/data/$(date +%Y-%m-%d)/informal.json
          cp data-formal.json dist/data/$(date +%Y-%m-%d)/formal.json
          git config --global user.email "yossthedev@gmail.com"
          git config --global user.name "Kubacash Service"
          git add dist/data/$(date +%Y-%m-%d)/informal.json
          git add dist/data/$(date +%Y-%m-%d)/formal.json
          git commit -m "Actualizar datos $(date +%Y-%m-%d)"
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
